"io" import

try
 "test1.req" io.readf
 err error
notry

io.putl

:error
 geterr ; get the error message

 errcl ; clear the error message (not required since we're immediately exiting, but still good practice)

 io.putl ; print the message

 1 exit
