"io" import

"test1.req" io.readf
err error

io.putl

:error
 geterr ; get the error message

 errcl ; clear the error message (not required since we're immediately exiting, but still good practice)

 io.putl ; print the message

 1 exit
